using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace UZIP2.Services
{
    public sealed record SidecarRecord(string FileName, string Algorithm, string Expected);

    // 一条校验文件比对的结论
    public sealed class SidecarCheck
    {
        public string Sidecar { get; set; }              // 校验文件名
        public int Total;                                // 记录条数
        public int Passed;
        public int Mismatched;
        public int Missing;
        public bool SelectedCovered;                     // 是否包含被选中的那个文件
        public bool SelectedOk;
        public string Detail = "";

        public bool PassedAll => Mismatched == 0 && Missing == 0 && Passed > 0;
    }

    public sealed class ChecksumReport
    {
        public string Path { get; set; }
        public string Sha256 { get; set; }               // 读取失败时为 null
        public string Error { get; set; }
        public List<SidecarCheck> Sidecars { get; } = new List<SidecarCheck>();
    }

    // 校验和：SHA-256 展示 + 旁挂校验文件（.sfv / .sha256 / .md5 / SHA256SUMS）逐条比对。
    // 下载多卷包时用它核对完整性，全部流式读取，不把文件整个塞进内存。
    public static class ChecksumService
    {
        static readonly string[] CommonSidecars = { "SHA256SUMS", "MD5SUMS", "checksums.txt", "checksum.md5", "sfv-list.txt" };

        public static string Sha256File(string path, IProgress<double> progress = null, CancellationToken ct = default)
        {
            using var sha = SHA256.Create();
            return HashFile(path, sha, progress, ct);
        }

        // CLI 写旁挂校验文件用: 支持 sha256/sha1/md5/crc32，返回小写十六进制。
        public static string Compute(string path, string algorithm, CancellationToken ct = default)
        {
            switch ((algorithm ?? "sha256").ToLowerInvariant())
            {
                case "md5": return HashWith(MD5.Create(), path);
                case "sha1": return HashWith(SHA1.Create(), path);
                case "crc32": return Crc32Hex(Crc32File(path, ct));
                default: return Sha256File(path, null, ct);
            }
        }

        static string HashFile(string path, HashAlgorithm hash, IProgress<double> progress, CancellationToken ct)
        {
            using var fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite, 1 << 18);
            long total = fs.Length, done = 0;
            var buf = new byte[1 << 18];
            int n;
            while ((n = fs.Read(buf, 0, buf.Length)) > 0)
            {
                ct.ThrowIfCancellationRequested();
                hash.TransformBlock(buf, 0, n, null, 0);
                done += n;
                if (progress != null && total > 0) progress.Report(done * 100.0 / total);
            }
            hash.TransformFinalBlock(buf, 0, 0);
            return ToHex(hash.Hash);
        }

        public static string ToHex(byte[] bytes)
        {
            var sb = new StringBuilder(bytes.Length * 2);
            foreach (var b in bytes) sb.Append(b.ToString("x2"));
            return sb.ToString();
        }

        public static uint Crc32File(string path, CancellationToken ct = default)
        {
            using var fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite, 1 << 18);
            var buf = new byte[1 << 18];
            uint crc = 0xFFFFFFFF;
            int n;
            while ((n = fs.Read(buf, 0, buf.Length)) > 0)
            {
                ct.ThrowIfCancellationRequested();
                for (int i = 0; i < n; i++)
                {
                    crc ^= buf[i];
                    for (int k = 0; k < 8; k++)
                        crc = (crc & 1) != 0 ? (crc >> 1) ^ 0xEDB88320u : crc >> 1;
                }
            }
            return crc ^ 0xFFFFFFFF;
        }

        public static string Crc32Hex(uint value) => value.ToString("x8");

        // ---------- 校验文件解析 ----------

        // 支持两种常见写法:
        //   coreutils:  <hex>[  | *]<filename>      (.sha256 / .md5 / SHA256SUMS)
        //   SFV:        <filename> <hex>            末尾的 "; CRC generated by" 之类注释跳过
        public static List<SidecarRecord> ParseSidecar(string text, string defaultAlgorithm)
        {
            var list = new List<SidecarRecord>();
            foreach (var raw in (text ?? "").Replace("\r\n", "\n").Split('\n'))
            {
                var line = raw.Trim();
                if (line.Length == 0 || line.StartsWith(";") || line.StartsWith("#")) continue;
                if (line.StartsWith("End of the validation file", StringComparison.OrdinalIgnoreCase)) continue;

                if (TryParseLine(line, defaultAlgorithm, out var rec)) list.Add(rec);
            }
            return list;
        }

        static bool TryParseLine(string line, string defaultAlgorithm, out SidecarRecord record)
        {
            record = null;
            // coreutils 风格: 哈希在前，两个空格或一个 * 分隔
            int sep = line.IndexOf("  ", StringComparison.Ordinal);
            if (sep > 0)
            {
                string head = line.Substring(0, sep).Trim();
                string tail = line.Substring(sep + 2).TrimStart('*', ' ');
                if (IsHash(head, out var algo))
                {
                    record = new SidecarRecord(CleanName(tail), algo ?? defaultAlgorithm, head.ToLowerInvariant());
                    return true;
                }
            }
            var parts = line.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length == 2)
            {
                if (IsHash(parts[1], out var algo))
                {
                    record = new SidecarRecord(CleanName(parts[0]), algo ?? defaultAlgorithm, parts[1].ToLowerInvariant());
                    return true;
                }
                if (IsHash(parts[0], out var algo2))
                {
                    record = new SidecarRecord(CleanName(parts[1]), algo2 ?? defaultAlgorithm, parts[0].ToLowerInvariant());
                    return true;
                }
            }
            return false;
        }

        static string CleanName(string name)
        {
            name = (name ?? "").Trim().Trim('"');
            return name.Replace('\\', '/');
        }

        static bool IsHash(string token, out string algorithm)
        {
            algorithm = null;
            if (string.IsNullOrEmpty(token)) return false;
            foreach (char c in token)
                if (!Uri.IsHexDigit(c)) return false;
            switch (token.Length)
            {
                case 8: algorithm = "crc32"; return true;
                case 32: algorithm = "md5"; return true;
                case 40: algorithm = "sha1"; return true;
                case 64: algorithm = "sha256"; return true;
                default: return false;
            }
        }

        // ---------- 发现旁挂校验文件 ----------

        public static List<string> FindSidecars(string targetPath)
        {
            var dir = Path.GetDirectoryName(targetPath) ?? "";
            if (!Directory.Exists(dir)) return new List<string>();
            string file = Path.GetFileName(targetPath);
            string stem = Path.GetFileNameWithoutExtension(targetPath);

            var candidates = new List<string>();
            foreach (var ext in new[] { ".sfv", ".sha256", ".sha1", ".md5" })
            {
                candidates.Add(Path.Combine(dir, file + ext));      // movie.7z.sfv
                candidates.Add(Path.Combine(dir, stem + ext));      // movie.sfv
            }
            foreach (var name in CommonSidecars) candidates.Add(Path.Combine(dir, name));

            var found = new List<string>();
            foreach (var c in candidates)
            {
                if (found.Any(f => string.Equals(f, c, StringComparison.OrdinalIgnoreCase))) continue;
                if (File.Exists(c)) found.Add(c);
            }
            return found;
        }

        static string AlgorithmForFile(string sidecar)
        {
            string ext = Path.GetExtension(sidecar).ToLowerInvariant();
            switch (ext)
            {
                case ".sfv": return "crc32";
                case ".md5": return "md5";
                case ".sha1": return "sha1";
                case ".sha256": return "sha256";
                default:
                    if (sidecar.IndexOf("md5", StringComparison.OrdinalIgnoreCase) >= 0) return "md5";
                    if (sidecar.IndexOf("sha1", StringComparison.OrdinalIgnoreCase) >= 0) return "sha1";
                    return "sha256";
            }
        }

        // ---------- 比对 ----------

        public static async Task<ChecksumReport> VerifyAsync(string targetPath, CancellationToken ct = default)
        {
            var report = new ChecksumReport { Path = targetPath };
            string selectedName = Path.GetFileName(targetPath);

            try { report.Sha256 = await Task.Run(() => Sha256File(targetPath), ct).ConfigureAwait(false); }
            catch (Exception ex) { report.Error = ex.Message; }

            var sidecars = FindSidecars(targetPath);
            foreach (var sidecar in sidecars)
            {
                ct.ThrowIfCancellationRequested();
                var check = await Task.Run(() => CheckSidecar(sidecar, selectedName), ct).ConfigureAwait(false);
                if (check != null) report.Sidecars.Add(check);
            }
            return report;
        }

        static SidecarCheck CheckSidecar(string sidecarPath, string selectedName)
        {
            List<SidecarRecord> records;
            try
            {
                records = ParseSidecar(File.ReadAllText(sidecarPath, Encoding.UTF8), AlgorithmForFile(sidecarPath));
            }
            catch (Exception) { return null; }
            if (records.Count == 0) return null;

            string dir = Path.GetDirectoryName(sidecarPath) ?? "";
            var check = new SidecarCheck { Sidecar = Path.GetFileName(sidecarPath), Total = records.Count };
            var problems = new List<string>();

            foreach (var rec in records)
            {
                string full = Path.Combine(dir, rec.FileName.Replace('/', Path.DirectorySeparatorChar));
                if (!File.Exists(full))
                {
                    check.Missing++;
                    if (SameName(rec.FileName, selectedName)) { check.SelectedCovered = true; check.SelectedOk = false; }
                    problems.Add(Path.GetFileName(rec.FileName) + " 缺失");
                    continue;
                }
                bool ok = Matches(full, rec);
                if (ok) check.Passed++;
                else
                {
                    check.Mismatched++;
                    problems.Add(Path.GetFileName(rec.FileName) + " 不符");
                }
                if (SameName(rec.FileName, selectedName))
                {
                    check.SelectedCovered = true;
                    check.SelectedOk = ok;
                }
            }

            check.Detail = problems.Count == 0
                ? $"{check.Passed}/{check.Total} 通过"
                : string.Join("；", problems.Take(3)) + (problems.Count > 3 ? $" 等 {problems.Count} 项" : "");
            return check;
        }

        static bool SameName(string recordName, string selectedName)
            => string.Equals(Path.GetFileName(recordName), selectedName, StringComparison.OrdinalIgnoreCase);

        static bool Matches(string file, SidecarRecord rec)
        {
            try
            {
                string actual;
                switch (rec.Algorithm)
                {
                    case "crc32": actual = Crc32Hex(Crc32File(file)); break;
                    case "md5": actual = HashWith(System.Security.Cryptography.MD5.Create(), file); break;
                    case "sha1": actual = HashWith(System.Security.Cryptography.SHA1.Create(), file); break;
                    default: actual = Sha256File(file); break;
                }
                return string.Equals(actual, rec.Expected, StringComparison.OrdinalIgnoreCase);
            }
            catch (Exception) { return false; }
        }

        static string HashWith(HashAlgorithm hash, string file)
            => HashFile(file, hash, null, CancellationToken.None);
    }
}
