using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UZIP2.Services;
using Xunit;

namespace UZIP2.Tests
{
    public class ChecksumServiceTests : IDisposable
    {
        readonly string _root;

        public ChecksumServiceTests()
        {
            _root = Path.Combine(Path.GetTempPath(), "UZipChecksum_" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(_root);
        }

        public void Dispose() { try { Directory.Delete(_root, true); } catch { } }

        string Write(string name, string content)
        {
            var p = Path.Combine(_root, name);
            File.WriteAllText(p, content, new UTF8Encoding(false));
            return p;
        }

        [Theory]
        [InlineData("abc", "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")]
        [InlineData("", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")]
        public void Sha256_matches_known_vectors(string content, string expected)
        {
            Assert.Equal(expected, ChecksumService.Sha256File(Write("a.bin", content)));
        }

        [Theory]
        [InlineData("abc", "352441c2")]
        [InlineData("123456789", "cbf43926")]
        public void Crc32_matches_known_vectors(string content, string expected)
        {
            Assert.Equal(expected, ChecksumService.Crc32Hex(ChecksumService.Crc32File(Write("a.bin", content))));
        }

        sealed class Captured : IProgress<double>
        {
            public double Max;
            public void Report(double value) { if (value > Max) Max = value; }
        }

        [Fact]
        public void Sha256_streams_large_files()
        {
            var p = Path.Combine(_root, "big.bin");
            var buf = new byte[3 << 20];
            new Random(3).NextBytes(buf);
            File.WriteAllBytes(p, buf);
            var captured = new Captured();
            var got = ChecksumService.Sha256File(p, captured);
            Assert.Equal(64, got.Length);
            Assert.Equal(100d, captured.Max, 1);
        }

        [Fact]
        public void Parse_handles_coreutils_sfv_and_comments()
        {
            string text = string.Join("\n",
                "; generated by SomeSFV 1.0",
                "movie.7z.001 352441c2",
                "movie.7z.002 cbf43926",
                "End of the validation file.",
                "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  empty.bin",
                "352441c2  *win\\path.bin",
                "");
            var recs = ChecksumService.ParseSidecar(text, "crc32");
            Assert.Equal(4, recs.Count);
            Assert.Equal("movie.7z.001", recs[0].FileName);
            Assert.Equal("crc32", recs[0].Algorithm);
            Assert.Equal("352441c2", recs[0].Expected);
            Assert.Equal("sha256", recs[2].Algorithm);
            Assert.Equal("empty.bin", recs[2].FileName);
            // 反斜杠统一成 /，二进制标记 * 被剥掉
            Assert.Equal("win/path.bin", recs[3].FileName);
        }

        [Fact]
        public void Parse_ignores_garbage()
        {
            Assert.Empty(ChecksumService.ParseSidecar("not a checksum line\n12345\n", "crc32"));
        }

        [Fact]
        public void Find_sidecars_covers_both_naming_styles()
        {
            var target = Write("movie.7z", "data");
            Write("movie.7z.sfv", "movie.7z 352441c2");
            Write("movie.md5", "e3b0c44298fc1c149afbf4c8996fb924  movie.7z");
            Write("SHA256SUMS", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  movie.7z");
            Write("unrelated.txt", "x");

            var found = ChecksumService.FindSidecars(target).Select(Path.GetFileName).ToList();
            Assert.Equal(3, found.Count);
            Assert.Contains("movie.7z.sfv", found);
            Assert.Contains("movie.md5", found);
            Assert.Contains("SHA256SUMS", found);
        }

        [Fact]
        public async Task Verify_reports_pass_for_a_matching_sfv()
        {
            var target = Write("movie.7z", "abc");
            Write("movie.7z.sfv", "movie.7z 352441c2\nmovie.part2 352441c2\n");

            var report = await ChecksumService.VerifyAsync(target);

            Assert.Equal("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad", report.Sha256);
            var check = Assert.Single(report.Sidecars);
            Assert.Equal("movie.7z.sfv", check.Sidecar);
            Assert.True(check.SelectedCovered);
            Assert.True(check.SelectedOk);
            Assert.Equal(1, check.Passed);
            Assert.Equal(1, check.Missing);           // movie.part2 不在盘上
            Assert.DoesNotContain("不符", check.Detail);
        }

        [Fact]
        public async Task Verify_flags_a_corrupted_file()
        {
            var target = Write("movie.7z", "abc");
            Write("movie.sha256", "000016bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad  movie.7z\n");

            var report = await ChecksumService.VerifyAsync(target);
            var check = Assert.Single(report.Sidecars);
            Assert.True(check.SelectedCovered);
            Assert.False(check.SelectedOk);
            Assert.Equal(1, check.Mismatched);
            Assert.Contains("不符", check.Detail);
            Assert.False(check.PassedAll);
        }

        [Fact]
        public async Task Verify_without_sidecar_still_returns_the_hash()
        {
            var target = Write("solo.zip", "abc");
            var report = await ChecksumService.VerifyAsync(target);
            Assert.Equal(64, report.Sha256.Length);
            Assert.Empty(report.Sidecars);
            Assert.Null(report.Error);
        }

        [Fact]
        public async Task Verify_of_a_missing_file_reports_an_error()
        {
            var report = await ChecksumService.VerifyAsync(Path.Combine(_root, "ghost.7z"));
            Assert.Null(report.Sha256);
            Assert.NotEmpty(report.Error);
        }
    }
}
